---
fixtures:
  repositories:
    disa_stig-el7-baseline:
      repo: https://github.com/simp/inspec-profile-disa_stig-el7
      branch: master
      target: spec/fixtures/inspec_deps/inspec_profiles/profiles
    concat: "https://github.com/simp/puppetlabs-concat"
    simplib: "https://github.com/simp/pupmod-simp-simplib"
    stdlib: "https://github.com/simp/puppetlabs-stdlib"
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
  symlinks:
    network: "#{source_dir}"
